system.enableEagerWorkflowStart:
  - value: true
frontend.workerVersioningDataAPIs:
  - value: true
frontend.workerVersioningWorkflowAPIs:
  - value: true
system.enableNexus:
  # enableNexus also controls transition history which can't be enabled now
  - value: false
component.nexusoperations.callback.endpoint.template:
  - value: http://localhost:7243/api/v1/namespaces/{{.NamespaceName}}/nexus/callback
component.callbacks.allowedAddresses:
  - value:
      - Pattern: "*"
        AllowInsecure: true
matching.queryWorkflowTaskTimeoutLogRate:
  - value: 1.0
history.ReplicationEnableUpdateWithNewTaskMerge:
  - value: true
history.enableWorkflowExecutionTimeoutTimer:
  - value: true
history.EnableReplicationTaskTieredProcessing:
  - value: true
history.persistenceMaxQPS:
  - value: 100000
    constraints: {}
frontend.persistenceMaxQPS:
  - value: 100000
    constraints: {}
history.shardUpdateMinInterval:
  - value: 1s