# Temporal-left:7233
# proxy-outbound-server-left: 38233
# proxy-mux: 11000
# proxy-outbound-server-right: 37233
# Temporal-right: 8233
clusterConnections:
  - name: "myCoolCluster-server"
    local:
      connectionType: "tcp" # TCP type must define both inbound and outbound
      tcpClient:
        address: "127.0.0.1:8233"
        tls:
          # certificatePath: "./proxycerts/temporal-internal.pem"
          # keyPath: "./proxycerts/temporal-internal.key"
          # remoteCAPath: "./proxycerts/temporal-internal.pem"
          # caServerName: "testhost"
          # skipCAVerification: true
      tcpServer:
        # Connects to "remote" temporal via proxy
        address: "127.0.0.1:37233"
        tls:
          certificatePath: "./proxycerts/temporal-internal.pem"
          keyPath: "./proxycerts/temporal-internal.key"
          remoteCAPath: "./proxycerts/temporal-internal.pem"
          caServerName: "localhost"
          skipCAVerification: false
    remote:
      connectionType: "mux-server" # One mux represents both inbound and outbound
      muxCount: 10
      muxAddressInfo:
        address: "127.0.0.1:11000"
        tls:
          certificatePath: "./proxycerts/client-account-cert.pem"
          keyPath: "./proxycerts/client-account-cert.key"
          remoteCAPath: "./proxycerts/clientowned.pem"
          caServerName: ""
          skipCAVerification: true
    failoverVersionIncrementTranslation:
      local: 100
      remote: 1000
    aclPolicy:
      allowedMethods:
        adminService:
          - AddOrUpdateRemoteCluster
          - DescribeCluster
          - DescribeMutableState
          - GetNamespaceReplicationMessages
          - GetWorkflowExecutionRawHistoryV2
          - ListClusters
          - StreamWorkflowReplicationMessages
      allowedNamespaces:
        - "left-ns"
#    namespaceTranslation:
#      mappings:
#        - localString: "leftName"
#          remoteString: "rightName"
#    searchAttributeTranslation:
#      namespaceMappings:
#        - name: "leftName"
#          namespaceId: "leftName"
#          mappings:
#            - localFieldName: "localSearchAttribute"
#              remoteFieldName: "remoteSearchAttribute"
#    localClusterHealthCheck:
#      protocol: "http"
#      listenAddress: "127.0.0.1:4911"
#    localClusterHealthCheck:
#      protocol: "http"
#      listenAddress: "127.0.0.1:4912"
metrics:
  prometheus:
    listenAddress: "0.0.0.0:9091"
profiling:
  pprofAddress: "localhost:6061"