clusterConnections:
  - name: "myCoolCluster"
    local:
      connectionType: "tcp" # TCP type must define both inbound and outbound
      tcpClient:
        address: "127.0.0.1:9001"
        tls:
          certificatePath: ""
          keyPath: ""
          remoteCAPath: ""
          caServerName: ""
          skipCAVerification: true
      tcpServer:
        address: "127.0.0.1:9002"
        tls:
          certificatePath: ""
          keyPath: ""
          remoteCAPath: ""
          caServerName: ""
          skipCAVerification: true
    remote:
      connectionType: "mux-server" # One mux represents both inbound and outbound
      muxCount: 10
      muxAddressInfo:
        address: "127.0.0.1:9004"
        tls:
          certificatePath: ""
          keyPath: ""
          remoteCAPath: ""
          caServerName: ""
          skipCAVerification: true
    aclPolicy:
      allowedMethods:
        adminService:
          - AddOrUpdateRemoteCluster
          - RemoveRemoteCluster
          - DescribeCluster
          - DescribeMutableState
          - GetNamespaceReplicationMessages
          - GetWorkflowExecutionRawHistoryV2
          - ListClusters
          - StreamWorkflowReplicationMessages
          - ReapplyEvents
          - GetNamespace # for EagerGetNamespace
      allowedNamespaces:
        - namespace1
        - namespace2
    failoverVersionIncrementTranslation:
      local: 100
      remote: 1000000
    replicationEndpoint: "127.0.0.1:9002"
    namespaceTranslation:
      mappings:
        - local: "localName"
          remote: "remoteName"
    searchAttributeTranslation:
      namespaceMappings:
        - name: "namespace1"
          namespaceId: "namespace-id-1"
          mappings:
            - localFieldName: "localSearchAttribute"
              remoteFieldName: "remoteSearchAttribute"
    remoteClusterHealthCheck:
      protocol: "http"
      listenAddress: "127.0.0.1:911"
    localClusterHealthCheck:
      protocol: "http"
      listenAddress: "127.0.0.1:912"
metrics:
  prometheus:
    listenAddress: "0.0.0.0:9090"
profiling:
  pprofAddress: "localhost:6060"