apiVersion: v1
kind: Service
metadata:
  name: {{ include "s2s-proxy.fullname" . }}
  labels:
    {{- include "s2s-proxy.labels" . | nindent 4 }}
spec:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # We strongly recommend using a headless service. Temporal uses gRPC internally, and kube-proxy's routing conflicts with
  # gRPC's client-side load balancer. More info https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  clusterIP: None
  ports:
  {{- $ports := (include "s2s-proxy.parsedPorts" . | fromYaml) }}
    - port: {{ $ports.egress }}
      targetPort: {{ $ports.egress }}
      protocol: TCP
      name: rpc-egress
  selector:
    {{- include "s2s-proxy.selectorLabels" . | nindent 4 }}
